name: update iptv

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:  # 允许手动触发


jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Modify JSON file
        run: |
          python3 ./iptv/iptv.py
        env:
          token: ${{ secrets.SECRET_TVBOX }}  # token
          owner: 'niuber'
          repo: 'iptv-api'
          workflow_id: 'main.yml'
          ref: 'master'
