name: update TVBox

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  sync-resource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TVBOX }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clean TVBoxOSC Directory
        run: |
          if [ -d "tvbox/TVBoxOSC/" ]; then
            rm -rf tvbox/TVBoxOSC/
            echo "TVBoxOSC directory cleaned."
          else
            echo "TVBoxOSC directory does not exist, skipping cleanup."
          fi



      - name: Update API Configuration
        run: |
          node ./tvbox/update-config.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "定时更新潇洒tvbox并更新lives、parses、ads信息，$(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed, check token permissions."
